Restaurant Page pull request
Grifo89/Javascript-restaurant-page pull request #1
Opened 2020-03-01 01:56 UTC by Grifo89

# This pull request has:
- A restaurant page made mostly based on javascript.

2020-03-02 22:02 UTC, MauricioRobayo requested changes
Congratulations, very nice project.

I like the structure that you have and the way you handled your SCSS partials.

There is a requirement that is not fully met:

* [x] It features a tabbed menu. When a tab is clicked the content is replaced ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)). Specifically, check the tab-switching logic inside of `ìndex.js`. You should have event listeners for each tab that wipes out the current contents and then runs the correct `tab module` to populate it again.

Status: __Request changes__.

2020-03-06 00:02 UTC, Grifo89 commented
Changes suggested are done.

2020-03-06 09:59 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/76073146-78d3c180-5f99-11ea-94a5-7a8cd3fad529.jpg)
### great job

2020-03-06 09:59 UTC, shloch commented on src/index.js
> +  }
great job

2020-03-18 15:52 UTC, merged